// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Naxxim.WeeCare.ChildManagement.Infrastructure.Data;

#nullable disable

namespace Naxxim.WeeCare.ChildManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ChildManagementDBContext))]
    [Migration("20230505193917_third Mig")]
    partial class thirdMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Naxxim.WeeCare.ChildManagement.Domain.Entites.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chronic_illness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChildId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Naxxim.WeeCare.ChildManagement.Domain.Entites.ChildIncidentDetails", b =>
                {
                    b.Property<int>("HealthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthId"));

                    b.Property<string>("ActionsPrises")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationOfTheIncident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChild")
                        .HasColumnType("int");

                    b.Property<string>("ParentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfIncident")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HealthId");

                    b.HasIndex("IdChild");

                    b.ToTable("ChildIncidentDetails");
                });

            modelBuilder.Entity("Naxxim.WeeCare.ChildManagement.Domain.Entites.ChildJournal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalId"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<string>("HealthCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Medication")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Nap_end")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Nap_start")
                        .HasColumnType("time");

                    b.HasKey("JournalId");

                    b.ToTable("ChildJournals");
                });

            modelBuilder.Entity("Naxxim.WeeCare.ChildManagement.Domain.Entites.ChildIncidentDetails", b =>
                {
                    b.HasOne("Naxxim.WeeCare.ChildManagement.Domain.Entites.Child", "child")
                        .WithMany("Incidents")
                        .HasForeignKey("IdChild")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("child");
                });

            modelBuilder.Entity("Naxxim.WeeCare.ChildManagement.Domain.Entites.Child", b =>
                {
                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
